### ISSUE TITLE
contact 2

### ISSUE THREAD

**Issue by djnaoki-mrn** [IgneButene/XTouch-FLStudio#3]
hi,
i'm working on a python midi script of x-touch as you made. the difference is that my script is designed for the Xctl mode of the x-touch. this mode allow you to use color of the screens and all the others functions of the controller.
i've use this documentation for coding my script : http://www.budgetfeatures.com/XctlDOC/Xctl%20Protocol%20for%20X-Touch%20V1.0.pdf

i contact you because i've got a probleme with my script, it makes fl studio crash randomly or during huge project loading.
you can see my code on my github : https://github.com/djnaoki-mrn/Behringer_X-Touch_for_FL_Studio_20/blob/main/Xctrl/device_Xctrl.py

i hope we talk soon : giordano-aurelien@hotmail.fr
have a good day, aurelien.

**Comment by bramdebouvere** [comment]
I've checked out your script, and I'm wondering if it's not due to too much print messages? I've noticed FL studio really slows down when there are a lot of print messages in the script output.

Perhaps this might also help?
http://www.budgetfeatures.com/XctlDOC/Xctl%20Protocol%20for%20X-Touch%20V1.0.pdf

**Comment by djnaoki-mrn** [comment]
hi,
i've solved my issue some month ago.
i've dont updated my github yet but it work prety fine now ! 
the software was crashing because in this mode (Xctl) the controller just flood FL Studio with SysEx messages.
FL studio was crashing mainly during project loading because during this time it not supose to receive SysEx mesages.
for solv my issue i've build up my own Midi > USB interface. This interface catch all the SysEx mesages form the controller and simply delete them befor they come to the PC and let the Midi message pass thrugh. She also let the midi and SysEx messages from the PC come to the controller. 
When i will get a little moment of time i will upload on github the new code for FL, the code for the Midi interface, the shematics of the midi interface, the 3d model for the 3d printed enclosure and some pictures.
thank you, have a good time.

**Comment by IgneButene** [comment]
Hey! Nice to hear you're making your own version. Now I've updated mine to be based on the very nicely done Bram's version! Thank you @bramdebouvere
