### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by RememberBeats** [IgneButene/XTouch-FLStudio#4]
I know you're not very active on there but just in case you see it...

It would be great if the fx plugins opened up when selected. Currently it only opens the parameters and allows you to control them, but you don't see the GUI.

I'm also wondering if it's possible to assign next pattern and previous pattern to any of the free buttons because in the script this function only works with arrows when you're with the channel rack focussed (audio inst button), but it's great to navigate between them when you're in the mixer for example.

Thank you for this amazing script.

**Comment by IgneButene** [comment]
Hey @RememberBeats,

Long time no speak, I suggest you try the new version I've just posted. It will now do exactly what you wanted - it will open the GUI. It's now re-written, based on another script.

The next/previous pattern feature is also now available. 
AND now you can also control the parameters of the generators on the channel rack! :) just head to Inst button next to Effects. :)

Happy usage! 😊
